config/routes.rb
Rails.application.routes.draw do

  get 'room_users/create'

  get 'room_users/destroy'

  get 'messages/create'

  root to: 'welcome#index'
  get '/signup', to: "registrations#new"
  post '/signup', to: "registrations#create"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :rooms do
    resources :room_users
    resources :users
  end
  resources :messages
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true
  belongs_to :user
  belongs_to :room

  after_create_commit { MessageBroadcastJob.perform_now self }
end

app/models/room.rb
class Room < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :room

  def set_moderator
    self.moderator = true
    self.save
  end

  def set_mute (mt)
    #self.mute = !self.mute
    self.mute = mt
    self.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :nickname, presence: true, uniqueness: true
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  helper_method :current_user, :log_in, :log_out, :logged_in?, :is_mute

  def current_user
      @current_user ||= User.find(cookies.signed[:user_id]) if cookies.signed[:user_id]
  end

  def log_in(user_id)
    cookies.signed[:user_id] = user_id
  end

  def logged_in?
    !!current_user
  end

  def log_out
    cookies.delete :user_id
    @current_user = nil
  end

  def is_mute(room_id)
    room = Room.find(room_id)
    room.room_users.where(user_id:  current_user.id).first.mute
  end

  protected
    def authenticate_user!
      redirect_to root_path unless logged_in?
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
# теперь не нужен контроллер
  def create
#    @message = Message.new(message_params) -
  end

  private
    def message_params
      params.require(:message).permit(:body, :room_id, :user_id)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  skip_before_action :authenticate_user!
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      log_in(user.id)
      redirect_to root_path
    else
      redirect_to signup_path, flash[:notice] =  user.errors.messages
    end

  end

  private
  def user_params
    params.require(:user).permit(:nickname)
  end

end

app/controllers/room_users_controller.rb
class RoomUsersController < ApplicationController
  before_action :set_room
  def create
    @user = User.find(params[:id])
    @room_user = @room.room_users.build(user_id: @user.id, room_id: @room.id, moderator: false, mute: false)
    @room_user.save
    respond_to do |format|
      format.html { redirect_to @room }
      format.js
    end
  end

  def update

    @room_user = RoomUser.find(params[:id])

    @room_user.set_mute (params[:mute]) if params[:mute]
    logger.info params[:mute]
    logger.info "_____________________________________________"
    @room_user.set_moderator if params[:moderator]
    logger.info params[:moderator]
  logger.info "_____________________________________________"
    redirect_to room_path(@room)
  end

  def destroy
    @room_user= RoomUser.find(params[:id])
    @room_user.destroy
    redirect_to room_path(@room)
  end

  def set_room
      @room = Room.find(params[:room_id])
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
#  skip_before_action :authenticate_user!
  def new
    @room= Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      @room_user = @room.room_users.build(user_id: current_user.id, room_id: @room.id, moderator: true, mute: false)
      @room_user.save
      logger.info @room_user
      respond_to do |format|
        format.html { redirect_to @room }
        format.js
    end
    else
      respond_to do |format|
        flash[:notice] = {error: ["Комната с таким названием существует"]}
        format.html { redirect_to new_room_path }
      end
    end
  end

  def edit
  end

  def update
  end

  def show
    @room = Room.find(params[:id])
    @users = @room.room_users
    @message = Message.new
    @messages= @room.messages.order(created_at: :desc).limit(100).reverse
  end

  def index
    #@rooms = Room.all
    @rooms = current_user.rooms
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_path }
      format.js
    end
  #  redirect_to rooms_path
  end

  private
    def room_params
      params.require(:room).permit(:title)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!
  def new
    @user=User.new
  end

  def create
    user=User.find_by(user_params)
    if user
      log_in (user.id)
      redirect_to root_path
    else
      redirect_to login_path, flash[:notice] =  user.errors.messages
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:nickname)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_room

  def index
    @users= User.where.not(id:  @room.room_users.select(:user_id))
  end

  def edit
    @user = User.find(params[:id])
    @room_user = @room.room_users.build(user_id: @user.id, room_id: @room.id, moderator: false)
    @room_user.save
    respond_to do |format|
      format.html { redirect_to @room }
      format.js
    end
  end

  private

    def set_room
        @room = Room.find(params[:room_id])
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/room_users_helper.rb
module RoomUsersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper

  def is_moderator(room)
    return room.room_users.where(user_id:  current_user.id).first.moderator
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/messages/_message.html.erb
<p><strong><%=message.user.nickname%>:</strong> <%=message.body%></p>

app/views/messages/_message_form.html.erb
       <%= form_for @message, remote:true, authenticity_token: true do |f|%>
       <%=f.label :body, "Ваше сообщение" %>
       <%= f.text_area :body, class: "form-control", id: "message_body" %>
       <%=f.hidden_field :room_id, value: @room.id %>
       <%=f.submit "Отправить", class: "btn btn-primary send_message", style: "display: block" , data: {send: "message"}%>
     <%end%>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/create.js.erb
console.log("messages create.js.erb")

app/views/room_users/_room_user.html.erb
<tr>
  <td ><%=room_user.user.nickname%> </td>

  <td  >
    <% if room_user.moderator %>
      модератор
    <% end%>
  </td>
  <td  >
    <% if is_moderator(@room) & ! room_user.moderator %>
      <%= link_to 'Сделать модератором', room_room_user_path(id: room_user.id,room_id: @room.id, moderator: true), method: :patch%> <br>
      <% if room_user.mute  %>
        <%= link_to 'Восстановить', room_room_user_path(id: room_user.id,room_id: @room.id, mute: false), method: :patch%>
         <br>
      <%else%>
        <%= link_to 'Забанить', room_room_user_path(id: room_user.id,room_id: @room.id, mute: true), method: :patch%>
      <%end%>
    <%end%>

    <% if (is_moderator(@room)) & (! room_user.moderator) %>
      <%= link_to 'Удалить', room_room_user_path(id: room_user.id, room_id: @room.id),
                method: :delete,
                data: { confirm: 'Вы уверены?' }%>
   <%end%>

  </td>

</tr>

app/views/room_users/create.html.erb
<h1>RoomUsers#create</h1>
<p>Find me in app/views/room_users/create.html.erb</p>

app/views/room_users/destroy.html.erb
<h1>RoomUsers#destroy</h1>
<p>Find me in app/views/room_users/destroy.html.erb</p>

app/views/rooms/_room.html.erb
<tr>
  <td>
    <%= link_to room.title, room_path(room) %>
  </td>
  <td>
    <% if is_moderator(room) %>
      <%= link_to "Удалить", room_path(room), remote: true,
                             method: :delete,
                             data: { confirm: 'Вы уверены?'}%>

    <%end%>
  </td>
</tr>

app/views/rooms/destroy.js.erb
localStorage.removeItem("room" + <%=@room.id%>)
location.reload()

app/views/rooms/edit.html.erb
<h1>Rooms#edit</h1>
<p>Find me in app/views/rooms/edit.html.erb</p>

app/views/rooms/index.html.erb
<h3 class="text-primary"><%= current_user.nickname.capitalize%>, <small class="text-primary" > для вас доступны следующие комнаты: </small></h3>
<% if @rooms.any? %>
  <table class= "table">
    <tbody>
      <%= render @rooms%>
    </tbody>
  </table>
  <%else %>

    <p>Вы не подписаны ни на одну комнату, создайте свою.</p>
  <% end %>

app/views/rooms/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <h2 id="log-in-title">Sign up</h2>
    <div class="auth-form well">
    <%= form_for(@room) do |f| %>

      <%= f.label :title, 'Название комнаты' %>
      <div class="input-group">
        <span class="input-group-addon">@</span>
          <%= f.text_field :title, class: "form-control"%>
      </div>

      <div class="actions">
        <%= f.submit "Сохранить", class: "btn btn-primary" %>
      </div>
    <% end %>
    </div>

      <%= render partial: 'layouts/flash_errors'%>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="row col-md-6 col-md-offset">
  <h1><%=@room.title%></h1>

<div class="panel panel-default pre-scrollable">

    <div class="panel-body" id="messages" data-room=<%= @room.id %>>
      <%= render partial: 'messages/message', collection: @messages%>
    </div>
</div>


  <%= render partial: 'messages/message_form', locals: {message: @message, room: @room}%>
</div>

<div class="row col-md-5 col-md-offset-1">
  <h1>Пользователи</h1>
      <table class="table ">
        <thead>
        </thead>
        <tbody id="tablebody" >
          <%= render partial: 'room_users/room_user', collection: @room.room_users%>
        </tbody  >
      </table>


    <% if is_moderator(@room) %>
      <%=link_to "Пригласить пользователя", room_users_path(room_id: @room.id) %>
    <%end%>
</div>

app/views/rooms/update.html.erb
<h1>Rooms#update</h1>
<p>Find me in app/views/rooms/update.html.erb</p>

app/views/users/_user.html.erb
<p> <%=user.user.nickname%>   <%=user.moderator%></p>

app/views/users/index.html.erb
<h1>Пользователи</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nickname %></td>
        <td><%= link_to 'Пригласить', room_room_users_path(id: user.id, room_id:@room.id), method: :post %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <%if current_user%>
    <h1 class = "h2 text-center"><%= current_user.nickname.capitalize%></h1>
  <%end%>

  <h3 class = "text-center"> Добро пожаловать в Чат!!!</h3>
<br>
  <p>Sign up or log in, then create a chatroom or browse existing rooms to start chatting.</p>
</div>