config/routes.rb
Rails.application.routes.draw do

  get 'room_users/create'

  get 'room_users/destroy'

  get 'messages/create'

  root to: 'welcome#index'
  get '/signup', to: "registrations#new"
  post '/signup', to: "registrations#create"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :rooms do
    resources :room_users
    resources :users
  end
  resources :messages
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true
  belongs_to :user
  belongs_to :room

  after_create_commit { MessageBroadcastJob.perform_now self }
end

app/models/room.rb
class Room < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :room

  def set_moderator
    self.moderator = true
    self.save
  end

  def set_mute (mt)
    #self.mute = !self.mute
    self.mute = mt
    self.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :nickname, presence: true, uniqueness: true
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  helper_method :current_user, :log_in, :log_out, :logged_in?, :is_mute

  def current_user
      @current_user ||= User.find(cookies.signed[:user_id]) if cookies.signed[:user_id]
  end

  def log_in(user_id)
    cookies.signed[:user_id] = user_id
  end

  def logged_in?
    !!current_user
  end

  def log_out
    cookies.delete :user_id
    @current_user = nil
  end

  def is_mute(room_id)
    room = Room.find(room_id)
    room.room_users.where(user_id:  current_user.id).first.mute
  end

  protected
    def authenticate_user!
      redirect_to root_path unless logged_in?
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
# теперь не нужен контроллер
  def create
#    @message = Message.new(message_params) -
  end

  private
    def message_params
      params.require(:message).permit(:body, :room_id, :user_id)
    end

end

app/controllers/room_users_controller.rb
class RoomUsersController < ApplicationController
  before_action :set_room
  def create
    @user = User.find(params[:id])
    @room_user = @room.room_users.build(user_id: @user.id, room_id: @room.id, moderator: false, mute: false)
    @room_user.save
    respond_to do |format|
      format.html { redirect_to @room }
      format.js
    end
  end

  def update

    @room_user = RoomUser.find(params[:id])

    @room_user.set_mute (params[:mute]) if params[:mute]
    logger.info params[:mute]
    logger.info "_____________________________________________"
    @room_user.set_moderator if params[:moderator]
    logger.info params[:moderator]
  logger.info "_____________________________________________"
    redirect_to room_path(@room)
  end

  def destroy
    @room_user= RoomUser.find(params[:id])
    @room_user.destroy
    redirect_to room_path(@room)
  end

  def set_room
      @room = Room.find(params[:room_id])
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
#  skip_before_action :authenticate_user!
  def new
    @room= Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      @room_user = @room.room_users.build(user_id: current_user.id, room_id: @room.id, moderator: true, mute: false)
      @room_user.save
      logger.info @room_user
      respond_to do |format|
        format.html { redirect_to @room }
        format.js
    end
    else
      respond_to do |format|
        flash[:notice] = {error: ["Комната с таким названием существует"]}
        format.html { redirect_to new_room_path }
      end
    end
  end

  def edit
  end

  def update
  end

  def show
    @room = Room.find(params[:id])
    @users = @room.room_users
    @message = Message.new
    @messages= @room.messages.order(created_at: :desc).limit(100).reverse
  end

  def index
    #@rooms = Room.all
    @rooms = current_user.rooms
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_path }
      format.js
    end
  #  redirect_to rooms_path
  end

  private
    def room_params
      params.require(:room).permit(:title)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!
  def new
    @user=User.new
  end

  def create
    user=User.find_by(user_params)
    if user
      log_in (user.id)
      redirect_to root_path
    else
      redirect_to login_path, flash[:notice] =  user.errors.messages
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:nickname)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_room

  def index
    @users= User.where.not(id:  @room.room_users.select(:user_id))
  end

  def edit
    @user = User.find(params[:id])
    @room_user = @room.room_users.build(user_id: @user.id, room_id: @room.id, moderator: false)
    @room_user.save
    respond_to do |format|
      format.html { redirect_to @room }
      format.js
    end
  end

  private

    def set_room
        @room = Room.find(params[:room_id])
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/room_users_helper.rb
module RoomUsersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper

  def is_moderator(room)
    return room.room_users.where(user_id:  current_user.id).first.moderator
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flash_errors.html.erb
<% if flash.notice %>
  <div class="alert alert-danger">
      <% flash.notice.each do |type, messages|%>
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span><%messages.each do |msg|%>
          <%=type%> <%=msg%>
        <%end%>
      <%end%>
  </div>
<%end%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "Чат", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= render partial: 'layouts/navbar_links' %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar_links.html.erb
<ul class="nav navbar-nav">
   <% if current_user %>
     <li>
       <%= link_to "Новая комната чата", new_room_path %>
     </li>
     <li>
       <%= link_to "Комнаты чата", rooms_path %>
     </li>
  <%end%>
</ul>

<ul class="nav navbar-nav navbar-right">
    <% if current_user %>
      <li>
        <%= link_to "Log Out", logout_path, method: "delete" %>
      </li>
    <% else%>
      <li><%= link_to "Sign Up", signup_path %></li>
      <li><%= link_to "Log In", login_path %></li>
    <%end%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: 'layouts/navbar' %>
  <div class="container"><!-- /.navbar-collapse -->
    <%= yield %>
  </div>
<br>
<br>
<br>
<br>
<br>
<br>
  <%=debug(params) if Rails.env%>
  </body>
</html>